"""empty message

Revision ID: 40b26c652ab8
Revises: 
Create Date: 2020-12-01 14:23:22.045899

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40b26c652ab8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('subscribe_list')
    op.drop_table('todo')
    op.drop_table('fcuser')
    op.add_column('model', sa.Column('category', sa.String(length=30), nullable=True))
    op.drop_column('model', 'register_at')
    op.add_column('model_detail', sa.Column('user_id', sa.Integer(), nullable=False))
    op.drop_constraint(None, 'model_detail', type_='foreignkey')
    op.create_foreign_key(None, 'model_detail', 'user', ['user_id'], ['id'])
    op.drop_column('model_detail', 'unregister_at')
    op.drop_column('model_detail', 'register_at')
    op.drop_column('model_detail', 'subscribe_list_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('model_detail', sa.Column('subscribe_list_id', sa.INTEGER(), nullable=False))
    op.add_column('model_detail', sa.Column('register_at', sa.DATETIME(), nullable=True))
    op.add_column('model_detail', sa.Column('unregister_at', sa.DATETIME(), nullable=True))
    op.drop_constraint(None, 'model_detail', type_='foreignkey')
    op.create_foreign_key(None, 'model_detail', 'subscribe_list', ['subscribe_list_id'], ['id'])
    op.drop_column('model_detail', 'user_id')
    op.add_column('model', sa.Column('register_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))
    op.drop_column('model', 'category')
    op.create_table('fcuser',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('userid', sa.VARCHAR(length=32), nullable=True),
    sa.Column('password', sa.VARCHAR(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('todo',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('fcuser_id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=256), nullable=True),
    sa.Column('status', sa.INTEGER(), nullable=True),
    sa.Column('due', sa.VARCHAR(length=64), nullable=True),
    sa.Column('tstamp', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['fcuser_id'], ['fcuser.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subscribe_list',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('subscribe_type', sa.VARCHAR(length=50), nullable=True),
    sa.Column('payment_type', sa.VARCHAR(length=50), nullable=True),
    sa.Column('total_price', sa.INTEGER(), nullable=True),
    sa.Column('total_quantity', sa.INTEGER(), nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
